fail_fast: true
repos:
  - repo: local
    hooks:
      - id: Name check
        name: Check sensitive info
        verbose: true
        language: system
        require_serial: true
        entry: bash -c "if [[ -d pre_commit_hooks ]]; then pre_commit_hooks/rtx.sh $@; fi"
      - id: IP check
        name: Check sensitive info
        verbose: true
        language: system
        require_serial: true
        entry: bash -c "if [[ -d pre_commit_hooks ]]; then pre_commit_hooks/ip.sh $@; fi"

  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry:  bash -c 'cd src/apiserver && make fmt'
        language: system
        files: src/apiserver/
        pass_filenames: false
      - id: vet
        name: vet
        entry:  bash -c 'cd src/apiserver && make vet'
        language: system
        files: src/apiserver/
        pass_filenames: false
      - id: lint
        name: lint
        entry: bash -c 'cd src/apiserver && make lint'
        language: system
        files: src/apiserver/
        pass_filenames: false

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        exclude: "^src/apiserver/docs/docs.go"
        files: ^src/apiserver/.*\.go$
        args:
          - --license-filepath
          - src/apiserver/license_header.txt        # defaults to: LICENSE.txt
          - --comment-style
          - ""